### ISSUE TITLE
Problem with property named nametag-in-range

### ISSUE THREAD

**Issue by TeQTabanca** [Tanguygab/TAB-Additions#31]
**If I add more than 1 number to the nametag-in-range property and use the /tab reload command each time, the player's nametag stays in the position it expects.**

### Minecraft Version: 1.12.2-Spigot

![image](https://user-images.githubusercontent.com/89253304/236787399-657b74da-e666-4b48-beb5-7789f63e26e2.png)
![image](https://user-images.githubusercontent.com/89253304/236787649-a9f3c7ec-c0b1-4718-bbf6-625c78516ce7.png)

**Comment by Tanguygab** [comment]
send your config

**Comment by TeQTabanca** [comment]
> send your config
[config.zip](https://github.com/Tanguygab/TAB-Additions/files/11421158/config.zip)

**Comment by Tanguygab** [comment]
Disable conditional-nametags

**Comment by TeQTabanca** [comment]
> Disable conditional-nametags

**Still same**

**Comment by Tanguygab** [comment]
disable it and restart, it should be fine afterwards

**Comment by TeQTabanca** [comment]
> disable it and restart, it should be fine afterwards

**I restarted the server but still the same**

**Comment by Tanguygab** [comment]
I don't know what's wrong then

**Comment by TeQTabanca** [comment]
**By the way, I tried the developer build of TAB-4.0.0-SNAPSHOT. The TAB-Additions plugin does not open.**

```
[21:37:12 INFO]: [TAB] Enabling TAB v4.0.0-SNAPSHOT
[21:37:12 INFO]: [TAB] Server version: 1.12.2 (v1_12_R1)
[21:37:12 INFO]: [TAB] Loaded NMS hook in 17ms
[21:37:12 INFO]: [TAB] Enabled in 222ms
[21:37:12 INFO]: [TAB-Additions] Enabling TAB-Additions v1.7.1
[21:37:12 ERROR]: Error occurred while enabling TAB-Additions v1.7.1 (Is it up to date?)
java.lang.NoClassDefFoundError: me/neznamy/tab/api/config/ConfigurationFile
        at io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot.onEnable(TABAdditionsSpigot.java:18) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [server.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: me.neznamy.tab.api.config.ConfigurationFile
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
```

**Comment by Tanguygab** [comment]
obviously, you'd expect thugs to break when a plugin switches from 3.x to 4.0. 
I did update TAB-Additions but didn't release it yet, here's a jar if you want to try![TAB-Additions-2.0.0-SNAPSHOT.jar.zip](https://github.com/Tanguygab/TAB-Additions/files/11435759/TAB-Additions-2.0.0-SNAPSHOT.jar.zip)

**Comment by TeQTabanca** [comment]
> obviously, you'd expect thugs to break when a plugin switches from 3.x to 4.0. I did update TAB-Additions but didn't release it yet, here's a jar if you want to try [TAB-Additions-2.0.0-SNAPSHOT.jar.zip](https://github.com/Tanguygab/TAB-Additions/files/11435759/TAB-Additions-2.0.0-SNAPSHOT.jar.zip)
> 
> Be aware that TAB-Additions 2.0.0 has a completely different config.yml, so you'll need to delete the entire folder to let it regenerate

**It works fine now, but when I use the nametag-in-range property, it throws an error in the error.log file.**

Error.log
```
09.05.2023 - 22:50:01 - [TAB v4.0.0-SNAPSHOT] Tried to modify non-existing team 7TeqTabancaA for player Test
09.05.2023 - 22:50:01 - [TAB v4.0.0-SNAPSHOT] Tried to modify non-existing team 6TestA for player TeqTabanca
```
Debug
```
[22:50:01 INFO]: TeqTabanca issued server command: /tab reload
[22:50:01 INFO]: [TAB] [DEBUG] Feature HeaderFooter processed unload in 0ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature BukkitPipelineInjector processed unload in 0ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature YellowNumber processed unload in 0ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature NameTag processed unload in 0ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature PlayerList processed unload in 1ms
[22:50:01 INFO]: [TAB] [TAB v4.0.0-SNAPSHOT] Tried to modify non-existing team 7TeqTabancaA for player Test
[22:50:01 INFO]: [TAB] [TAB v4.0.0-SNAPSHOT] Tried to modify non-existing team 6TestA for player TeqTabanca
[22:50:01 INFO]: [TAB] [DEBUG] Feature NametagInRange processed unload in 0ms
[22:50:01 INFO]: [TAB] Disabled in 2ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature PlaceholderManagerImpl processed load in 1ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature HeaderFooter processed load in 1ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature BukkitPipelineInjector processed load in 1ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature YellowNumber processed load in 0ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature Sorting processed load in 0ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature NameTag processed load in 0ms
[22:50:01 INFO]: [TAB] [DEBUG] Feature PlayerList processed load in 1ms
[22:50:01 INFO]: [TAB] Enabled in 12ms
```

**Comment by Tanguygab** [comment]
I'll check, when I get home

**Comment by TeQTabanca** [comment]
> I'll check, when I get home

**By the way, when you turn on the unlimited-nametag-mode feature in the TAB plugin's config.yml file, and set the nametag-in-range property to more than 1, the player's name tag stays in the position it expects after the /tab reload command.**

**Comment by TeQTabanca** [comment]
**Why doesn't the nametag-in-range property work properly with the conditional-nametags and unlimited-nametag-mode property?**

**Comment by TeQTabanca** [comment]
**Any chance of adding a fix to make it work properly?**

**Comment by Tanguygab** [comment]
> **By the way, when you turn on the unlimited-nametag-mode feature in the TAB plugin's config.yml file, and set the nametag-in-range property to more than 1, the player's name tag stays in the position it expects after the /tab reload command.**
Works fine for me
> **Why doesn't the nametag-in-range property work properly with the conditional-nametags and unlimited-nametag-mode property?**
nametag-in-range and conditional-nametags aren't meant to be used together. Either way, I fixed the error here

[TAB-Additions-2.0.0-SNAPSHOT.zip](https://github.com/Tanguygab/TAB-Additions/files/11441448/TAB-Additions-2.0.0-SNAPSHOT.zip)

**Comment by TeQTabanca** [comment]
> > **By the way, when you turn on the unlimited-nametag-mode feature in the TAB plugin's config.yml file, and set the nametag-in-range property to more than 1, the player's name tag stays in the position it expects after the /tab reload command.**
> 
> Works fine for me
> 
> > **Why doesn't the nametag-in-range property work properly with the conditional-nametags and unlimited-nametag-mode property?**
> 
> nametag-in-range and conditional-nametags aren't meant to be used together. Either way, I fixed the error here
> 
> [TAB-Additions-2.0.0-SNAPSHOT.zip](https://github.com/Tanguygab/TAB-Additions/files/11441448/TAB-Additions-2.0.0-SNAPSHOT.zip)

**The moment I turn on the conditional-nametags feature, the nametag-in-range feature is not used, and the nametag-in-range feature is still not used even though I turned off the conditional-nametags feature. Finally, the issue with the unlimited-nametag-mode attribute seems to be fixed in this version.**

**Comment by TeQTabanca** [comment]
**In the anti-override.log file this text rarely appears.**

`10.05.2023 - 14:09:32 - [TAB v4.0.0-SNAPSHOT] Something just tried to add player Test into team ETest (expected team: ￿26TestA)`

**Comment by TeQTabanca** [comment]
> > **The moment I turn on the conditional-nametags feature, the nametag-in-range feature is not used, and the nametag-in-range feature is still not used even though I turned off the conditional-nametags feature. Finally, the issue with the unlimited-nametag-mode attribute seems to be fixed in this version.**
> 
> I know, that's on purpose
> 
> > **In the anti-override.log file this text rarely appears.**
> > ```
> > 10.05.2023 - 14:09:32 - [TAB v4.0.0-SNAPSHOT] Something just tried to add player Test into team ETest (expected team: �26TestA)
> > ```
> 
> this should not appear anymore, delete the file and reload

**Every time the players log into the server, it gives this message.**

```
10.05.2023 - 15:17:58 - [TAB v4.0.0-SNAPSHOT] Something just tried to add player TeqTabanca into team d36b830e-e2de-4 (expected team: ￿20TeqTabancaA)
10.05.2023 - 15:18:07 - [TAB v4.0.0-SNAPSHOT] Something just tried to add player Test into team 478071e1-cc8c-4 (expected team: ￿26TestA)
```

**Comment by Tanguygab** [comment]
that's not TAB-Additions

**Comment by TeQTabanca** [comment]
**In the last build of the TAB plugin, your plugin gives an error in the console. ([Error](https://paste.gg/p/anonymous/f06ea77680fb4d9aa30c3a5084cdf7c5))**

**Comment by Tanguygab** [comment]
open new issues when you get a new error unrelated to the current issue.
I'll fix it when I come back home
